### ISSUE TITLE
unknown shorthand flag: 'n' in -n

### ISSUE THREAD

**Issue by 0xVIC** [cyberbutler/RedDrop#6]
Using your command:
`docker run -t -v "$PWD/uploads:/reddrop/uploads" -v "$PWD/logs:/reddrop/logs" -p "80:80" -n reddrop cyberbutler/reddrop-exfil-server -h`
Error:
`unknown shorthand flag: 'n' in -n`

Replacing -n for --name
New error:
`docker run -t -v "$PWD/uploads:/reddrop/uploads" -v "$PWD/logs:/reddrop/logs" -p "80:80" --name reddrop cyberbutler/reddrop-exfil-server -h`

`Unable to find image 'cyberbutler/reddrop-exfil-server:latest' locally
docker: Error response from daemon: pull access denied for cyberbutler/reddrop-exfil-server, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.`

**Comment by cyberbutler** [comment]
@0xVIC My apologies, I updated the Readme, I had the incorrect docker image listed, you can find it here instead: `cyberbutler/reddrop`

```bash
docker run -t -v "$PWD/uploads:/reddrop/uploads" -v "$PWD/logs:/reddrop/logs" -p "80:80" --name reddrop cyberbutler/reddrop -h
```
